### ISSUE TITLE
Having Scala 2.13 along Scala 2.12

### ISSUE THREAD

**Issue by aluscent** [bioscala/bioscala#8]
I created this issue to discuss how we can start upgrading the project's Scala version to 2.13. As per email conversations with Juhan, we think we have 2 options:
- Having 1 branch and porting that branch to Scala 2.13
- Having 2 branches for Scala 2.12 and 2.13

The latter has the luxury of compatibility with Spark, along with supporting users with use cases in Scala 3. I go with the second option. 😄

**Comment by jtnystrom** [comment]
I agree that having two branches for now makes sense, since the majority of Spark users are still on Scala 2.12 as I understand (but slowly migrating to 2.13). Some time in the future there might no longer be a need for a 2.12 branch.

**Comment by aluscent** [comment]
Sounds great! Let's create a new branch so I can create a pull request on it. As a suggestion, the branch name can be something like Scala-2.13.

**Comment by jtnystrom** [comment]
Created the scala-2.13 branch.
